# 01 - Análisis Exploratorio de Datos (EDA)
## Proyecto: Predicción de Abandono (Churn) - AndesLink
**Alumno:** Facundo Zubeldia  
**Materia:** Laboratorio de Minería de Datos - ISTEA

In [2]:
import sys
import os

# Esto te dice exactamente qué ejecutable de Python está usando el notebook
print(f"Ruta del ejecutable: {sys.executable}")

# Esto te confirma en qué carpeta estás parado (debería ser /notebooks)
print(f"Directorio actual: {os.getcwd()}")

# Verificamos si las librerías clave están disponibles en este kernel
try:
    import pandas
    import mlflow
    print("✅ Entorno correctamente configurado con Pandas y MLflow")
except ImportError:
    print("❌ Error: Faltan librerías. ¿Seguro seleccionaste el venv del proyecto?")

Ruta del ejecutable: /home/facundozubeldia/Documentos/fz_workspace/Lab-Mineria-de-Datos/venv/bin/python
Directorio actual: /home/facundozubeldia/Documentos/fz_workspace/Lab-Mineria-de-Datos/notebooks
✅ Entorno correctamente configurado con Pandas y MLflow

In [3]:
import pandas as pd
import numpy as np
import sklearn as sk

df = pd.read_csv("/home/facundozubeldia/Documentos/fz_workspace/Lab-Mineria-de-Datos/data/churn_sintetico.csv")

df.head(5)

,tenure_months,monthly_charge,total_charges,support_tickets,late_payments,avg_monthly_usage_gb,contract_type,payment_method,internet_service,has_streaming,has_security_pack,num_products,region,customer_age,is_promo,churn
0,7,58.23,326.50,2,1,81.83,mensual,transferencia,cable,0,1,3,centro,53,1,1
1,56,56.75,3154.21,0,2,96.52,anual,debito,fibra,0,0,4,centro,53,0,0
2,48,78.84,3864.31,3,2,93.60,bianual,efectivo,movil,1,1,4,centro,73,1,1
3,32,79.74,2511.40,0,0,28.95,bianual,debito,movil,0,1,4,norte,25,0,1
4,32,55.37,1735.51,3,0,126.90,anual,efectivo,fibra,1,0,2,oeste,61,1,0

In [4]:
df['churn'].value_counts(normalize=True)

churn
0    0.6596
1    0.3404
Name: proportion, dtype: float64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   tenure_months         5000 non-null   int64
 1   monthly_charge        5000 non-null   float64
 2   total_charges         5000 non-null   float64
 3   support_tickets       5000 non-null   int64
 4   late_payments         5000 non-null   int64
 5   avg_monthly_usage_gb  5000 non-null   float64
 6   contract_type         5000 non-null   object
 7   payment_method        5000 non-null   object
 8   internet_service      5000 non-null   object
 9   has_streaming         5000 non-null   int64
 10  has_security_pack     5000 non-null   int64
 11  num_products          5000 non-null   int64
 12  region                5000 non-null   object
 13  customer_age          5000 non-null   int64
 14  is_promo              5000 non-null   int64
 15  churn                 5000 non-null   int64
dtypes: float64(3), int64(9), object(4)
memory usage: 625.1+ KB

In [8]:
df.describe()

,tenure_months,monthly_charge,total_charges,support_tickets,late_payments,avg_monthly_usage_gb,has_streaming,has_security_pack,num_products,customer_age,is_promo,churn
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,36.407200,65.273282,2371.156582,1.710400,0.69700,120.528458,0.668000,0.539800,2.516400,47.825800,0.386200,0.340400
std,20.839776,17.963425,1555.943231,1.304788,0.84388,49.745297,0.470978,0.498463,1.111746,17.615684,0.486926,0.473891
min,1.000000,15.000000,50.000000,0.000000,0.00000,5.000000,0.000000,0.000000,1.000000,18.000000,0.000000,0.000000
25%,18.000000,53.060000,1100.357500,1.000000,0.00000,86.505000,0.000000,0.000000,2.000000,32.000000,0.000000,0.000000
50%,36.000000,64.965000,2162.810000,2.000000,0.00000,120.030000,1.000000,1.000000,3.000000,48.000000,0.000000,0.000000
75%,55.000000,77.362500,3432.657500,2.000000,1.00000,154.100000,1.000000,1.000000,4.000000,63.000000,1.000000,1.000000
max,72.000000,127.170000,9083.060000,8.000000,5.00000,324.400000,1.000000,1.000000,4.000000,78.000000,1.000000,1.000000